version: '3.7'

networks:
  traefik-public:
    external: true

services:
  td2-tools:
    image: ${IMAGE_NAME:-ghcr.io/kacpermalachowski/td2-tools:latest}
    networks:
      - traefik-public
    ports:
      - 3001:3000
    deploy:
      mode: replicated
      replicas: 2
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      update_config:
        parallelism: 1
        delay: 20s
        order: stop-first
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.td2-tool-http.rule=Host(`td2.kacpermalachowski.pl`)
        - traefik.http.routers.td2-tools-http.entrypoints=http
        - traefik.http.routers.td2-tools-http.middlewares=https-redirect
        - traefik.http.routers.td2-tools-https.rule=Host(`td2.kacpermalachowski.pl`)
        - traefik.http.routers.td2-tools-https.entrypoints=https
        - traefik.http.routers.td2-tools-https.tls=true
        - traefik.http.routers.td2-tools-https.tls.certresolver=le
        - traefik.http.services.td2-tools.loadbalancer.server.port=3000