import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import Sceneries from "../../data/Sceneries";
import generateTrainNo, { TrainTypes } from "../components/NumberGenerator/generateNumber";
import styles from '../styles/Home.module.css';

const TrainNumber: NextPage = () => {

  const [startZone, setStartZone] = useState(1);
  const [endZone, setEndZone] = useState(1);
  const [trainType, setTrainType] = useState(TrainTypes.Ekspres);

  console.log(trainType)


  return (
    <>
    <Head>
      <title>Generate Train Number</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className={styles.container}>
      <Link href="/">
        Powrót
      </Link>
      <main className={styles.main}>
        <form className={styles.card}>
          <label style={{ display: "block" }}>
            Starting Scenery
            <select name="start-zone" value={startZone} onChange={(e) => setStartZone(Number.parseInt(e.target.value))}>
              {Sceneries.map((e,i) => (
                <option key={e.name} value={i}>{e.name}</option>
              ))}
            </select>
          </label>
          <label style={{ display: "block" }}>
            Destination/Final Scenery:
            <select name="end-zone" value={endZone} onChange={(e) => setEndZone(Number.parseInt(e.target.value))}>
              {Sceneries.map((e,i) => (
                <option key={e.name} value={i}>{e.name}</option>
              ))}
            </select>
          </label>
          <label style={{ display: "block" }}>
            Train Type:
            <select name="train-type"value={TrainTypes[trainType]} onChange={(e) => setTrainType(TrainTypes[e.target.value])}>
              { Object.keys(TrainTypes).filter((el) => { return isNaN(Number(el)) }).map((key: any) => (
                <option key={key} value={key}>{key}</option>
              ))}
            </select>
          </label>
          <span style={{ display: "block" }}>Your train number for today is: {generateTrainNo(Sceneries[startZone].construtionZone,Sceneries[endZone].construtionZone,trainType)}</span>
        </form>
      </main>
    </div>
    </>
  )
}

export default TrainNumber;
